### ISSUE TITLE
pyseer with no distance and lm p-values don't match

### ISSUE THREAD

**Issue by SarahNadeau** [mgalardini/pyseer#113]
I am trying to check pyseer p-values for an association test without any distance matrix: phenotype = beta * SNP presence + error. When I fit this model in R using lm, I get very different p-values than when I fit the model in pyseer (looking at the filter-pvalue column). Is there a reason why I should expect different p-values from lm and pyseer without a distance matrix?

Here is the pyseer command I ran:
$PYSEER \
--phenotypes $WORKDIR/example_phenotypes.txt \
--pres $WORKDIR/example_variants.txt \
--continuous \
--no-distances > $WORKDIR/example_pyseer_output.txt

And here is the example data, the pyseer output, and my R script with output for a single SNP. 

Please let me know if any other information would be helpful!

[example_phenotypes.txt](https://github.com/mgalardini/pyseer/files/4244869/example_phenotypes.txt)
[example_variants.txt](https://github.com/mgalardini/pyseer/files/4244870/example_variants.txt)
[example_pyseer_output.txt](https://github.com/mgalardini/pyseer/files/4244871/example_pyseer_output.txt)
[check_pyseer_script.txt](https://github.com/mgalardini/pyseer/files/4244875/check_pyseer_script.txt)

**Comment by SarahNadeau** [comment]
I just noticed that the lrt-pvalue does match the R lm output. My question is probably super simple now, but what is the filter-pvalue column and how is it calculated?

**Comment by mgalardini** [comment]
Hi, relieved to hear that the lrt-pvalue matches with your own model! Since you have run the fixed effects model on a continuous phenotype, the prefiltering p-value is derived using a t-test between samples with the variant vs. samples without. It's there because it's a fast way to prefilter variants that are most certainly not associated, although we actually reccommend to run the associations on all variants, so that qq-plots can be drawn and the lrt-pvalue threshold can be derived from the number of unique observed patterns (i.e. see the `--output-patterns` option and the `scripts/count_patterns.py` script). Hope this helps!

**Comment by SarahNadeau** [comment]
Thanks! That makes sense :)
