### ISSUE TITLE
phylogeny_distance.py result not symmetric

### ISSUE THREAD

**Issue by RicardoGCCR** [mgalardini/pyseer#124]
Hi, 
I am running pyseer with the output of panaroo (https://gtonkinhill.github.io/panaroo/#/post/pwas), and when I run:

python ~/pyseer/scripts/phylogeny_distance.py --lmm ./panaroo_output/core_tree.treefile > phylogeny_K.tsv 

using the output of IQ-tree, the resulting K matrix is not symmetric (attached). Does this table look ok to you?

If I continue with the pipeline the p_values obtained are very strange: for example, some genes present only on 2-4 genomes of one of the groups (p<1,07E-05). HOWEVER, there are a few genes on my data that are present in 29/30 genomes of only one group BUT the p value is just 0.313.

Any idea what is going on?

I attached: 
phylogeny_distance.py #script used
core_tree.treefile # from IQ-tree
phylogeny_K.tsv # output

Thank you in advance for your help, 

Ricardo

**Comment by RicardoGCCR** [comment]
Sorry, here the files:
https://gist.github.com/RicardoGCCR/2fa9d35b8cabb9bda98723566fb1b726
Thanks

**Comment by johnlees** [comment]
Hi Ricardo,

The matrix appears to be symmetric, at least at first glance. The diagonal is non-zero, but that is expected.

The results you report may well be a result of population structure, or may be spurious due to low minor allele frequency. I don't know how many samples you have, but you want to at least set `--min-af` and `--max-af` to exclude anything that's present in fewer than five samples, or absent in fewer than five samples.

To check the population structure, you could also run with `--no-distances` to see how the p-values change. Comparing the adjusted and unadjusted values can also be informative.

Hope that helps!

**Comment by RicardoGCCR** [comment]
Hi John, 
Thank you for the explanation. I was confused with the non-zero diagonal and though that the problem was there. 
I am running 4 groups of bacteria, each one built with 30 genomes (120 in total). I
I will check your suggestions. 
Thanks again, 
Ricardo

**Comment by mgalardini** [comment]
Closing for lack of updates
