### ISSUE TITLE
pytest :test_load_structure fails

### ISSUE THREAD

**Issue by linaule** [mgalardini/pyseer#191]
Hi!
I have installed pyseer through cloning the git repository and now am running a pytest. However, the test_load_structure keeps on failing.
Here are my error messages:

tests/input_test.py::TestLoadFunctions::test_load_structure FAILED  
----
tests/input_test.py:77
----
E           TypeError: __init__() takes from 1 to 2 positional arguments but 3 positional arguments (and 3 keyword-only arguments) were given

pyseer/input.py:116: TypeError

What could have gone wrong?

**Comment by johnlees** [comment]
This is due to this line I believe: https://github.com/mgalardini/pyseer/blob/33e8e4fdde281dbec7bc3be93bced412efbec5c4/pyseer/input.py#L116-L118

I think scikit-learn may have changed its API recently: https://scikit-learn.org/stable/modules/generated/sklearn.manifold.MDS.html

So this would need to become:
```
        mds = manifold.MDS(n_components=max_dimensions, metric=metric_mds, n_jobs=n_cpus,
                           dissimilarity='precomputed',
                           random_state=seed)
```

Can you confirm which version of sklearn you are using? (`conda list` or similar)
