### ISSUE TITLE
GT KeyError with own data

### ISSUE THREAD

**Issue by sarahbuzz** [mgalardini/pyseer#48]
Hello,

I'm really excited to use this software, I've been hoping someone produces a GWA method for prokaryotes that accounts for clonality and lineage effects!

I ran into a KeyError when I tried to run pyseer on my data:

Traceback (most recent call last):

  File "/home/sbusby/miniconda3/bin/pyseer", line 10, in <module>
    sys.exit(main())
  File "/home/sbusby/miniconda3/lib/python3.6/site-packages/pyseer/__main__.py", line 450, in main
    options.cpu*options.block_size))
  File "/home/sbusby/miniconda3/lib/python3.6/multiprocessing/pool.py", line 274, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/sbusby/miniconda3/lib/python3.6/multiprocessing/pool.py", line 376, in _map_async
    iterable = list(iterable)
  File "/home/sbusby/miniconda3/lib/python3.6/site-packages/pyseer/input.py", line 471, in iter_variants
    sample_order)
  File "/home/sbusby/miniconda3/lib/python3.6/site-packages/pyseer/input.py", line 298, in read_variant
    var_name = read_vcf_var(line_in, d)
  File "/home/sbusby/miniconda3/lib/python3.6/site-packages/pyseer/input.py", line 375, in read_vcf_var
    for haplotype in call['GT']:
  File "pysam/libcbcf.pyx", line 3439, in pysam.libcbcf.VariantRecordSample.__getitem__
  File "pysam/libcbcf.pyx", line 792, in pysam.libcbcf.bcf_format_get_value
**KeyError: 'invalid FORMAT: GT'**

I have the genotype field populated in the VCFs and the merged VCF (I can attach my data if needed). I have pysam version 0.14.1. I'm using the distances flag with a phylogenetic tree that I generated using RAxML. I created the distances.tsv with the phylogeny_distance.py.

I also tried running pyseer using the test data, `core_genome_aln.tree`, but there is not output when I run: `python pyseer-master/scripts/phylogeny_distance.py core_genome_aln.tree`. I wanted to make sure it wasn't a formatting problem on my end but I can't test the `--distances` flag on the test data provided.

What could I be doing wrong?

Thanks for your help!

Sarah

**Comment by mgalardini** [comment]
Hi Sarah,

thanks for your interest in pyseer! Would you be able to share your VCF and tree with me? It might be easier to track down the source of this error.

Best,
Marco

**Comment by sarahbuzz** [comment]
See attached.
[merged.vcf.gz](https://github.com/mgalardini/pyseer/files/2210458/merged.vcf.gz)

[tree-newick.txt](https://github.com/mgalardini/pyseer/files/2210459/tree-newick.txt)

**Comment by mgalardini** [comment]
Hi Sarah,

The second bug can be fixed by upgrading the pandas python library (there's a bug described here: https://github.com/pandas-dev/pandas/issues/21471#issuecomment-397151205). I suggest `pip install pandas --upgrade`, but it might depend on how packages are installed on your system.

I'll report on the VCF one shortly.
Marco

**Comment by mgalardini** [comment]
The VCF error is due to the lines in your VCF file that do not have GT calls, like this one:

`1	424045	.	A	AC	.	PASS	ADP=97;WT=0;HET=0;HOM=1;NC=0;CSQ	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.	.`

I'm implementing and testing a fix for this, but if you are in a hurry you can just filter those out and re-run pyseer on the filtered VCF file.

Hope this helps,
Marco

**Comment by mgalardini** [comment]
I believe this is now fixed; you can either filter your VCF or install the latest `pyseer` version from here.

M

**Comment by sarahbuzz** [comment]
Hi Marco,

Oh goodness, thanks so much for finding that! I don't have the GT field populated in my VCFs so I had to write a `sed` substitute to add that field in. The consequence field is usually filled but I guess there's an issue with VEP; this wasn't a case I was considering in my substitute. I've fixed that and I can run the version that is available on conda without `pyseer` complaining :)

Thank you so much for your help! I'm excited to see the results!

Sarah
