### ISSUE TITLE
matrix inversion error for null model

### ISSUE THREAD

**Issue by kallote** [mgalardini/pyseer#69]
Hi,
I ran pyseer as follows
"pyseer --phenotypes phenotypes_file --kmers fsm_kmers.txt.gz --distances mash.tsv --min-af 0.01 --max-af 0.99 --cpu 16 > pyseer.assoc"
and go the following error:
Read 1282 phenotypes
Detected binary phenotype
Structure matrix has dimension (1282, 1282)
Analysing 1282 samples found in both phenotype and structure matrix
Matrix inversion error for null model
Could not fit null model, exiting

Any ideas where this comes from? I did try to flip one value in the phenotype file like you have written in some previous issues, but that didn't help.
pyseer version 1.2.0 at the Sanger farm.

Cheers,
-Teemu-

**Comment by kallote** [comment]
Hi John,
I did try to run with the --no-distances and pyseer does output kmers in that case (but exits before filtering based on p-value, I think). 

I created the distance matrix again with mash and the file seems the same as before. I didn't see anything obviously wrong with it.

If you could look what's wrong, I'm working on lustre:
/../../../team212/tk9/EPECs/EVAsEPECs/

**Comment by johnlees** [comment]
Seems to be some issue with the optimiser, I can get it to work using a different maximisation method. I'll add this to the code for future versions.

For now, I was able to get it to work by using metric rather than classic MDS:
```
python ~jl11/installations/pyseer/pyseer-runner.py --phenotypes phenotypes_file --kmers fsm_kmers.txt.gz --distances mash.tsv --min-af 0.01 --max-af 0.99 --mds metric
```
I'm not sure what version the central install on the farm is, but if this doesn't work you can use the version in my home, after activating my environment:
```
source ~jl11/pathogen_nfs/large_installations/miniconda3/bin/activate ~jl11/pathogen_nfs/large_installations/miniconda3/envs/conda_py36
```

Also, you might consider using the `--lmm` mode instead
