### ISSUE TITLE
Incomplete k-mer annotation 

### ISSUE THREAD

**Issue by Morteza-M-Saber** [mgalardini/pyseer#88]
Im trying to annotate some kmers found by pyseer in v.cholera and I have some problem in creating reference.txt to be used by annotate_hits_pyseer.  

In tutorial it is said 

> "We’ll start by creating a references.txt file listing the annotations we wish to use:", 

but actually there is no instruction in the [tutorial](https://pyseer.readthedocs.io/en/master/tutorial.html#interpreting-significant-k-mers)

The required format is also a bit hard to comprehend.
```
File of reference annotations. First column fasta
                        sequence, second column gff annotation, third column
                        'ref' or 'draft'
```
Am I missing something here or the tutorial is actually incomplete in this section?

Thanks,

**Comment by johnlees** [comment]
Hi Masih,

Yes, it looks like this is a bit unclear, I'll add more info to the documentation. There is a little more in this section of the usage: https://pyseer.readthedocs.io/en/master/usage.html#annotating-k-mers

The idea is that you have one reference per line which the k-mers will be mapped to iteratively, in the order they appear in the file. Each reference needs a .fa for the sequence (for mapping) and a .gff for the annotation (to lift over the gene names to the output).

You can also designate genomes as reference or draft (i.e. a complete genome with good annotation, or an automated assembly and annotation). The difference between the two is only that reference genomes are mapped to using bwa mem, so allow mismatches, and draft genomes require exact matches.

My original idea was that you would provide some references you liked at the top, then give all the draft genomes you used to count the k-mers in the first place in the rest of the file, so that everything would be mapped.

**Comment by Morteza-M-Saber** [comment]
Thanks for the explanation John.
That is very clear now.
One minor point, just to improve the documentation, is that the 'phandango_mapper' transforms all chromosome names to 26 which is fine for majority of bacterial species with only one chromosome. But the visualization in phandango is not correct for species like vibrio cholera which has two chromosomes.
 I merged the two chromosomes and given the gff from NCBI it seems to work fine in phandango. Not sure if this was the best way so I think it would be good to mention the best practice to be done in such situations in tutorial.
