### ISSUE TITLE
Suggestions for using elastic net whole-genome models for GWAS

### ISSUE THREAD

**Issue by apredeus** [mgalardini/pyseer#92]
Hello, 

thank you for a great tool - it's amazing to see all the different capabilities (e.g. burden testing) in one suite. Great work! 

I've recently come across a preprint that tested various GWAS approaches using simulated data (https://www.biorxiv.org/content/10.1101/795492v1), and they seem to come to a conclusion that whole-genome elastic net models substantially outperform other approaches, especially for variants with weaker effects. I seem to have such dataset, at least as far as I can tell. So I've had few questions about using the "wg enet" option. 

- is it OK to use k-mers from fsm-lite for this approach? I see manual suggesting using unitigs, similarly to how DBGWAS does it. However fsm-lite output doesn't seem like it is k-mers in the first place - the strings are all of different length. 
- what is the significance cutoff, and is there a way to report variants that are less than significant? 

Any other suggestions would be greatly appreciated.

**Comment by johnlees** [comment]
Thanks for the kind comments! In answer to your questions:

* Yes, fsm-lite k-mers will work, but the memory usage is likely to be very high, hence the suggestion of unitigs (of which there are fewer). The fsm-lite output are k-mers, but of different lengths rather than a fixed k. They are 'informative' k-mers in the selected length range, as described in the [original SEER paper](http://www.nature.com/articles/ncomms12797).
* There isn't a significance threshold in the same way, as the elastic net does not give p-values for each variant. Those selected (i.e. that appear in the output) are the variants that give the best prediction from cross-validation. A p-value will also be calculated using the fixed effects model (if distances are provided), but note that this is a univariate test and not the p-value from the elastic net itself.

Hope that helps. Let me know if you have further questions

**Comment by cizydorczyk** [comment]
So to be clear,

The p-values reported from JUST the elastic net analysis are NOT association p-values. To get association p-values, one could test variants (unitigs, etc.) reported by the elastic net using a univariate model?

From my understanding, the elastic net model already accounts for population structure to some degree, does it not? If so, if testing variants found by the elastic net analysis, is a second method of population structure correction required?

Thank you!
Conrad

**Comment by johnlees** [comment]
The elastic net, and related options such as `--sequence-reweighting` and `--lineage-clusters` _only_ relate to the beta values (effect sizes), and the selection variants that appear in the output. The implicit accounting of population structure is seen by the fact that many variants have their effect size as zero (and are not printed in the output).

The p-values columns are **totally separate from the elastic net**.
Each variant selected by the elastic net undergoes a univariate test using the SEER model, giving an unadjusted association, and if distances are provided also the p-value from a fixed effect regression.
(the LMM is not automated yet, but you can merge results if you wish to assign LMM p-values to these variants)

The current idea is that the elastic net can be useful for selecting variants, forming predictors and calculating heritability. The univariate p-values, which we don't currently get at from the elastic net, can be useful for further ranking the results. We may add to or change this in the future, but if we do I promise clearer column headers the the results to make this clear.

I hope that clarifies this issue, but let me know if there are further questions.

**Comment by cizydorczyk** [comment]
That really helps, thank you!!
